package Bitwise;

/*389. Find the Difference

Total Accepted: 12912
Total Submissions: 26899
Difficulty: Easy

Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.

https://leetcode.com/problems/find-the-difference/

Idea: 
based on 2 facts: 
	0 ^ n = n
	n ^ n = 0

so xor all elements in two strings, then only the diff one is left


*/

public class _389_Find_the_Difference {
	public char findTheDifference(String s, String t) {
		char result = 0;
		for (int i = 0; i < s.length(); i++)
			result ^= s.charAt(i);
		for (int i = 0; i < t.length(); i++)
			result ^= t.charAt(i);
		return result;
	}
}
